### PR TITLE
Change compat-data and preset-env to 7.9.0

### PR DESCRIPTION
**Pull request by code-geek**
When doing a fresh install of earthdata-search, I got the following error on running `npm start`:

```
> earthdata-search@1.0.0 start /Users/ashish/projects/earthdata_delete
> NODE_ENV=development webpack-dev-server --open --config static.webpack.config.dev.js

internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /Users/ashish/projects/earthdata_delete/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /Users/ashish/projects/earthdata_delete/node_modules/@babel/preset-env/lib/index.js
- /Users/ashish/projects/earthdata_delete/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/ashish/projects/earthdata_delete/node_modules/@babel/core/lib/config/files/index.js
- /Users/ashish/projects/earthdata_delete/node_modules/@babel/core/lib/index.js
- /Users/ashish/projects/earthdata_delete/node_modules/@babel/register/lib/cache.js
- /Users/ashish/projects/earthdata_delete/node_modules/@babel/register/lib/node.js
- /Users/ashish/projects/earthdata_delete/node_modules/@babel/register/lib/index.js
- /Users/ashish/projects/earthdata_delete/static.webpack.config.common.js
- /Users/ashish/projects/earthdata_delete/static.webpack.config.dev.js
- /Users/ashish/projects/earthdata_delete/node_modules/webpack-cli/bin/utils/convert-argv.js
- /Users/ashish/projects/earthdata_delete/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/ashish/projects/earthdata_delete/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Module._compile (/Users/ashish/projects/earthdata_delete/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Object.newLoader [as .js] (/Users/ashish/projects/earthdata_delete/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/ashish/projects/earthdata_delete/node_modules/@babel/preset-env/lib/index.js:29:44)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Module._compile (/Users/ashish/projects/earthdata_delete/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Object.newLoader [as .js] (/Users/ashish/projects/earthdata_delete/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ashish/projects/earthdata_delete/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js',
    '/Users/ashish/projects/earthdata_delete/node_modules/@babel/preset-env/lib/index.js',
    '/Users/ashish/projects/earthdata_delete/node_modules/@babel/core/lib/config/files/plugins.js',
    '/Users/ashish/projects/earthdata_delete/node_modules/@babel/core/lib/config/files/index.js',
    '/Users/ashish/projects/earthdata_delete/node_modules/@babel/core/lib/index.js',
    '/Users/ashish/projects/earthdata_delete/node_modules/@babel/register/lib/cache.js',
    '/Users/ashish/projects/earthdata_delete/node_modules/@babel/register/lib/node.js',
    '/Users/ashish/projects/earthdata_delete/node_modules/@babel/register/lib/index.js',
    '/Users/ashish/projects/earthdata_delete/static.webpack.config.common.js',
    '/Users/ashish/projects/earthdata_delete/static.webpack.config.dev.js',
    '/Users/ashish/projects/earthdata_delete/node_modules/webpack-cli/bin/utils/convert-argv.js',
    '/Users/ashish/projects/earthdata_delete/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! earthdata-search@1.0.0 start: `NODE_ENV=development webpack-dev-server --open --config static.webpack.config.dev.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the earthdata-search@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ashish/.npm/_logs/2020-05-15T14_56_22_305Z-debug.log
```

I found a reference to the error message: `Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'` on the [nodejs issues page](https://github.com/nodejs/node/issues/32852).

The [suggested solution](https://github.com/nodejs/node/issues/32852#issuecomment-613655150) is to update `@babel/preset-env` to `7.9.0`.

I also needed to add `"@babel/compat-data": "^7.9.0"`.

With these two changes, I was able to get `npm start` running.

### CODE REVIEW

**Comment by macrouch** [comment]
@code-geek Thanks for the PR! Looks like you need to commit the changes to `package-lock.json` after running `npm install` as well

**Comment by abbottry** [comment]
@code-geek What version of Node are you running locally?

**Comment by code-geek** [comment]
> @code-geek What version of Node are you running locally?

```
❯ node -v
v14.2.0
❯ npm -v
6.14.5
```

**Comment by abbottry** [comment]
AWS has just recently started supported Node 12.x -- so as a best practice we run the version of node that AWS supports (even though this only applies to Lambda). The amount of babel libraries needed in dependent on the version of Node running when you run `npm install`, and in this case you're running a version of node that was release less than a month ago. Before we merge more polyfills into the application, can you please try to downgrade your Node to 12.x and trying this all again? 

I can/will update our README to suggest this, but we have an `.nvmrc` file that is used by us and our deployments (I'm seeing now that we never updated it when we bumped our lambdas up to 12.x so we'll need to update that as well) to determine Node versions -- I'd suggest using NVM when running Node locally.

**Comment by code-geek** [comment]
> AWS has just recently started supported Node 12.x -- so as a best practice we run the version of node that AWS supports (even though this only applies to Lambda). The amount of babel libraries needed in dependent on the version of Node running when you run `npm install`, and in this case you're running a version of node that was release less than a month ago. Before we merge more polyfills into the application, can you please try to downgrade your Node to 12.x and trying this all again?
> 
> I can/will update our README to suggest this, but we have an `.nvmrc` file that is used by us and our deployments (I'm seeing now that we never updated it when we bumped our lambdas up to 12.x so we'll need to update that as well) to determine Node versions -- I'd suggest using NVM when running Node locally.

Thank you. I'll definitely try running it with node 12.x and get back to you.

**Comment by code-geek** [comment]
As suggested, I reset the changes on this branch, updated my .nvmrc to `v12.16.3` and ran all the steps in the README.

I got an error about [Node Sass](https://github.com/sass/node-sass/issues/2536) which I was able to fix. 

Confirming that the project is running successfully without the changes on this PR.

**Comment by abbottry** [comment]
Thanks @code-geek we'll get the `.nvmrc` updated in a PR soon with some README updates.
